/**
 * G78-1-CORRECTED — Transform-and-import harness for pushOutcomesToRemote.
 *
 * Actually calls the REAL pushOutcomesToRemote function with a stubbed but
 * functioning AsyncStorage, capturing the queue's actual contents before and
 * after each call. Inspection of the source is not evidence.
 *
 * Pattern: same transform-and-import approach as item57_realbar_replay_harness.ts.
 * Stubs: react-native (Platform) and @react-native-async-storage/async-storage
 * are replaced with in-memory equivalents. The @supabase/supabase-js import is
 * kept — it is a pure JS package that works in Node/bun.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

interface StoredTradeOutcome {
  signalId: string;
  entryPrice: number;
  exitPrice: number;
  result: 'WIN' | 'LOSS';
  pnl: number;
  confidence: number;
  features: unknown;
  timestamp: string | number | Date;
  misleadingFeatures?: unknown;
  signalDuration?: number;
  direction?: 'BUY' | 'SELL';
  realizedR?: number;
  isScratch?: boolean;
  featureSchemaVersion?: number;
}

interface PushResult {
  upserted: number;
  queued: number;
  failed: number;
  failureDetail: string | null;
}

interface PushStats {
  pushAttempts: number;
  pushSuccesses: number;
  pushFailures: number;
  rowsPushed: number;
  failuresByStatus: Record<string, number>;
  suppressedByReason: Record<string, number>;
  lastFailureBody: string | null;
}

const SANDBOX_DIR = 'scripts/__sandbox_g78__';
const SANDBOX_FILE = join(SANDBOX_DIR, 'learningStore.replay.ts');

/**
 * Rewrite learningStore.ts into a Node-runnable module.
 * Only IMPORTS are stubbed. No logic is altered.
 */
function buildSandboxModule(): string {
  const src = readFileSync('services/learningStore.ts', 'utf-8');
  const lines = src.split('\n');

  const stubs = [
    '// AUTO-GENERATED by g78_corrected_harness.ts. Do not edit.',
    '// Imports are stubbed for Node; ALL logic below is byte-identical to',
    '// services/learningStore.ts as shipped.',
    'export const sandboxStorage = new Map<string, string>();',
    'const AsyncStorage = {',
    '  async getItem(key: string): Promise<string | null> { return sandboxStorage.get(key) ?? null; },',
    '  async setItem(key: string, value: string): Promise<void> { sandboxStorage.set(key, value); },',
    '  async removeItem(key: string): Promise<void> { sandboxStorage.delete(key); },',
    '};',
    'const Platform = { OS: "web" as const };',
    'export function __resetPushClientForTest(): void { pushClient = null; }',
    '',
  ];

  const dropPrefixes = [
    'import { Platform } from',
    'import AsyncStorage from',
  ];

  const kept: string[] = [];
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    const matched = dropPrefixes.some((p) => line.startsWith(p));
    if (matched) {
      let stmt = line;
      while (!stmt.includes(';') && i + 1 < lines.length) {
        i += 1;
        stmt += lines[i];
      }
      i += 1;
      continue;
    }
    kept.push(line);
    i += 1;
  }

  const body = kept.join('\n').replace(/from "@/g, 'from "../../');

  return `${stubs.join('\n')}\n${body}\n`;
}

async function main(): Promise<void> {
  const line = '='.repeat(84);
  console.log(`\n${line}`);
  console.log('G78-1-CORRECTED — TRANSFORM-AND-IMPORT HARNESS');
  console.log(line);

  // 1. Generate sandbox module
  mkdirSync(SANDBOX_DIR, { recursive: true });
  const generated = buildSandboxModule();
  writeFileSync(SANDBOX_FILE, generated, 'utf-8');
  console.log(`  sandbox module: ${SANDBOX_FILE} (${generated.split('\n').length} lines)`);

  // 2. Load env
  const env: Record<string, string> = {};
  try {
    for (const envLine of readFileSync('.env', 'utf-8').split('\n')) {
      const trimmed = envLine.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eq = trimmed.indexOf('=');
      if (eq < 0) continue;
      env[trimmed.slice(0, eq)] = trimmed.slice(eq + 1).replace(/^["']|["']$/g, '');
    }
  } catch { /* fall through */ }

  const SUPA_URL = env.EXPO_PUBLIC_SUPABASE_URL;
  const VALID_KEY = env.EXPO_PUBLIC_SUPABASE_ANON_KEY;
  if (!SUPA_URL || !VALID_KEY) {
    console.error('Missing Supabase credentials');
    process.exit(1);
  }

  // 3. Set env for FORCED FAILURE (invalid key)
  process.env.EXPO_PUBLIC_SUPABASE_URL = SUPA_URL;
  process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY = 'sb_invalid_key_for_g78_test';

  // 4. Import sandbox module
  const mod = (await import(`../${SANDBOX_FILE}`)) as {
    pushOutcomesToRemote: (outcomes: StoredTradeOutcome[]) => Promise<PushResult>;
    getPendingRemotePushCount: () => number;
    sandboxStorage: Map<string, string>;
    __resetPushClientForTest: () => void;
    getOutboundPushStats: () => PushStats;
  };

  // 5. Test outcomes
  const now = Date.now();
  const testOutcomes: StoredTradeOutcome[] = [
    {
      signalId: 'test_g78_corrected_001',
      entryPrice: 3450.0,
      exitPrice: 3455.0,
      result: 'WIN',
      pnl: 5.0,
      confidence: 0.72,
      features: { rsi: 55.0 },
      timestamp: now,
      direction: 'BUY',
      realizedR: 1.0,
    },
    {
      signalId: 'test_g78_corrected_002',
      entryPrice: 3460.0,
      exitPrice: 3455.0,
      result: 'LOSS',
      pnl: -5.0,
      confidence: 0.68,
      features: { rsi: 45.0 },
      timestamp: now,
      direction: 'SELL',
      realizedR: -1.0,
    },
  ];

  // 6. BEFORE state
  console.log('\n  BEFORE any call:');
  console.log(`    sandboxStorage keys: [${[...mod.sandboxStorage.keys()].join(', ') || '(empty)'}]`);
  console.log(`    pendingRemotePush count: ${mod.getPendingRemotePushCount()}`);

  // 7. CALL 1: forced failure (invalid key -> HTTP 401)
  console.log('\n  CALL 1: pushOutcomesToRemote(testOutcomes) with INVALID key');
  const result1 = await mod.pushOutcomesToRemote(testOutcomes);
  console.log(`    return value: ${JSON.stringify(result1)}`);

  // 8. AFTER CALL 1: verify queue state
  console.log('\n  AFTER CALL 1 (forced failure):');
  console.log(`    pendingRemotePush count: ${mod.getPendingRemotePushCount()}`);
  const q1 = mod.sandboxStorage.get('pending_remote_push_v1');
  console.log(`    sandboxStorage has 'pending_remote_push_v1': ${q1 ? 'YES' : 'NO'}`);
  if (q1) {
    const parsed = JSON.parse(q1) as StoredTradeOutcome[];
    console.log(`    queue length: ${parsed.length}`);
    console.log(`    queue signal IDs: [${parsed.map((o) => o.signalId).join(', ')}]`);
  }

  // 9. Reset pushClient, switch to valid key
  mod.__resetPushClientForTest();
  process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY = VALID_KEY;

  // 10. CALL 2: successful retry (valid key -> HTTP 201)
  console.log('\n  CALL 2: pushOutcomesToRemote([]) with VALID key');
  const result2 = await mod.pushOutcomesToRemote([]);
  console.log(`    return value: ${JSON.stringify(result2)}`);

  // 11. AFTER CALL 2: verify queue drained
  console.log('\n  AFTER CALL 2 (successful retry):');
  console.log(`    pendingRemotePush count: ${mod.getPendingRemotePushCount()}`);
  const q2 = mod.sandboxStorage.get('pending_remote_push_v1');
  console.log(`    sandboxStorage has 'pending_remote_push_v1': ${q2 ? 'YES' : 'NO'}`);
  if (q2) {
    const parsed = JSON.parse(q2) as StoredTradeOutcome[];
    console.log(`    queue length: ${parsed.length}`);
  }

  // 12. Push stats
  const stats = mod.getOutboundPushStats();
  console.log('\n  PUSH STATS:');
  console.log(`    pushAttempts: ${stats.pushAttempts}`);
  console.log(`    pushSuccesses: ${stats.pushSuccesses}`);
  console.log(`    pushFailures: ${stats.pushFailures}`);
  console.log(`    rowsPushed: ${stats.rowsPushed}`);
  console.log(`    failuresByStatus: ${JSON.stringify(stats.failuresByStatus)}`);

  console.log(`\n  DONE`);
  console.log(line);
}

main().catch((err: unknown) => {
  console.error('g78_corrected_harness failed:', err instanceof Error ? err.message : String(err));
  process.exit(1);
});
