/**
 * ITEM D — DERIVE THE TP LADDER FROM EVIDENCE (READ-ONLY. NOTHING IS IMPLEMENTED.)
 *
 * CANONICAL OUTCOME SET (stated once, used for every number in this report):
 *   369 export signals, re-resolved by the REAL resolveSignalWithBars
 *   (imported, never mirrored) with { fromScratch: true, evalNowMs = last real bar },
 *   win predicate R > 0, denominator = all 369.
 *   Baseline (stored geometry, live lock): WR 63.1%  PF 1.16  EV +0.0605R  net +$111.2
 *
 * DATA-SOURCE RULE: gold_m1_bars read DIRECTLY from Supabase via the anon key.
 *   No Rork backend. No GC=F / TwelveData. No priceHistory ticks.
 *
 * METHOD: every cell re-runs the REAL resolver over all 369 signals against real
 * bars. The resolver is parameterised via its optional `ladder` hook (defaults
 * reproduce live behaviour exactly — proven by the baseline reproducing
 * +0.0605R after the hook was added). There is no mirror and no approximation.
 *
 * STRUCTURAL NOTE: sweeping TP1 as an R-multiple tests a STRUCTURAL change —
 * the live engine sets TP1 in ABSOLUTE PIPS, so its R-multiple is an emergent
 * quotient of a pinned numerator over an ATR-driven denominator. Both
 * parameterisations are therefore swept and reported side by side.
 *
 * TRANSFER CAVEAT: these 369 signals were generated by the PRE-F tick-driven
 * engine. See the MFE/MAE section for the property that carries transfer.
 */
import { writeFileSync } from "node:fs";

import { resolveSignalWithBars, type LadderOverride } from "../services/signalResolver";
import type { OhlcBar } from "../services/barStore";
import type { TradingSignal } from "../types/trading";
import { buildCanonical, parseExport, toTradingSignal, type ParsedSignal, type Canon } from "./preconditions";

const PIP = 0.1;

// ─── cell definition ────────────────────────────────────────────────────────
type Tp1Mode = "R" | "PIP";
type Tp23Mode = "abs" | "scaled";
type LockFamily = "fracTP1" | "fracR";

interface LockSpec {
  id: string;
  family: LockFamily;
  /** ordered value within the family (fraction of TP1, or fraction of R) */
  value: number;
  cap: boolean;
  ladder: LadderOverride;
}

interface Cell {
  tp1Mode: Tp1Mode;
  tp1Value: number;
  lock: LockSpec;
  tp23: Tp23Mode;
}

interface CellResult {
  cell: Cell;
  n: number;
  wr: number;
  pf: number;
  ev: number;
  net: number;
  evBuy: number;
  evSell: number;
  wrBuy: number;
  wrSell: number;
  pfBuy: number;
  pfSell: number;
  nBuy: number;
  nSell: number;
  /** SL_HIT under the baseline ladder that ends R>0 under this cell */
  conversions: number;
  /** R>0 under the baseline that becomes a full loss under this cell */
  reversions: number;
  /** ladders where TP1 is at or beyond TP2 (degenerate under 'abs') */
  degenerate: number;
  /** signals where the 5-pip lock floor binds */
  floorBinds: number;
  /** signals where the 0.9 x TP1 lock cap binds */
  capBinds: number;
  /** per-signal R, index-aligned with the canonical row order (for paired stats) */
  rs: number[];
}

function lockSpecs(): LockSpec[] {
  const out: LockSpec[] = [];
  for (const f of [0.3, 0.4, 0.5]) {
    for (const cap of [true, false]) {
      out.push({
        id: `TP1x${f.toFixed(1)}${cap ? "" : "/nocap"}`,
        family: "fracTP1",
        value: f,
        cap,
        ladder: { lockFractionOfTP1: f, applyLockCap: cap },
      });
    }
  }
  // Incumbent parameterisation: lock = 0.35 x realised stop distance.
  for (const cap of [true, false]) {
    out.push({
      id: `R0.35${cap ? "" : "/nocap"}`,
      family: "fracR",
      value: 0.35,
      cap,
      ladder: { lockFractionOfR: 0.35, applyLockCap: cap },
    });
  }
  return out;
}

const LOCKS = lockSpecs();
const LOCK_BY_ID = new Map(LOCKS.map((l) => [l.id, l]));

// ─── geometry rebuild ───────────────────────────────────────────────────────
const r1 = (x: number): number => Number(x.toFixed(1));

interface Geom {
  sig: TradingSignal;
  stop: number;
  degenerate: boolean;
}

function buildGeometry(p: ParsedSignal, cell: Cell): Geom {
  const stop = Math.abs(p.entry - p.sl);
  const isBuy = p.direction === "BUY";
  const sgn = isBuy ? 1 : -1;

  const oldTp1d = Math.abs(p.tp1 - p.entry);
  const oldTp2d = Math.abs(p.tp2 - p.entry);
  const oldTp3d = Math.abs(p.tp3 - p.entry);

  const newTp1d = cell.tp1Mode === "R" ? cell.tp1Value * stop : cell.tp1Value * PIP;

  let newTp2d: number;
  let newTp3d: number;
  if (cell.tp23 === "abs") {
    newTp2d = oldTp2d;
    newTp3d = oldTp3d;
  } else {
    const k = oldTp1d > 0 ? newTp1d / oldTp1d : 1;
    newTp2d = oldTp2d * k;
    newTp3d = oldTp3d * k;
  }

  const sig = toTradingSignal(p);
  sig.tp1 = r1(p.entry + sgn * newTp1d);
  sig.tp2 = r1(p.entry + sgn * newTp2d);
  sig.tp3 = r1(p.entry + sgn * newTp3d);
  return { sig, stop, degenerate: newTp1d >= newTp2d };
}

/** Reproduce the resolver's lock arithmetic to report where floor/cap bind. */
function lockBinding(sig: TradingSignal, spec: LockSpec): { floor: boolean; cap: boolean } {
  const stop = Math.abs(sig.entryPrice - sig.sl);
  const tp1d = Math.abs(sig.tp1 - sig.entryPrice);
  const minDelta = 5 * PIP;
  const base = spec.family === "fracTP1" ? tp1d * spec.value : stop * spec.value;
  const floored = Math.max(base, minDelta);
  const ceiling = spec.cap && tp1d > 0 ? tp1d * 0.9 : Number.POSITIVE_INFINITY;
  return { floor: floored > base, cap: floored > ceiling };
}

// ─── cell evaluation ────────────────────────────────────────────────────────
interface Ctx {
  sigs: ParsedSignal[];
  slices: OhlcBar[][];
  evalNowMs: number;
  baselineR: number[];
}

function evalCell(cell: Cell, ctx: Ctx): CellResult {
  const rs: number[] = [];
  const dirs: ("BUY" | "SELL")[] = [];
  let net = 0;
  let degenerate = 0;
  let floorBinds = 0;
  let capBinds = 0;

  for (let i = 0; i < ctx.sigs.length; i++) {
    const p = ctx.sigs[i];
    const g = buildGeometry(p, cell);
    if (g.degenerate) degenerate++;
    const b = lockBinding(g.sig, cell.lock);
    if (b.floor) floorBinds++;
    if (b.cap) capBinds++;

    const out = resolveSignalWithBars(g.sig, ctx.slices[i], {
      fromScratch: true,
      evalNowMs: ctx.evalNowMs,
      ladder: cell.lock.ladder,
    });
    const pnl = p.direction === "BUY" ? out.exitPrice - p.entry : p.entry - out.exitPrice;
    rs.push(pnl / g.stop);
    dirs.push(p.direction);
    net += pnl;
  }

  const agg = (sel: (i: number) => boolean) => {
    const v: number[] = [];
    for (let i = 0; i < rs.length; i++) if (sel(i)) v.push(rs[i]);
    const w = v.filter((x) => x > 0);
    const l = v.filter((x) => x < 0);
    const gw = w.reduce((a, b) => a + b, 0);
    const gl = Math.abs(l.reduce((a, b) => a + b, 0));
    return {
      n: v.length,
      wr: v.length ? (w.length / v.length) * 100 : 0,
      pf: gl > 0 ? gw / gl : Number.POSITIVE_INFINITY,
      ev: v.length ? v.reduce((a, b) => a + b, 0) / v.length : 0,
    };
  };

  const all = agg(() => true);
  const buy = agg((i) => dirs[i] === "BUY");
  const sell = agg((i) => dirs[i] === "SELL");

  let conversions = 0;
  let reversions = 0;
  for (let i = 0; i < rs.length; i++) {
    if (ctx.baselineR[i] < 0 && rs[i] > 0) conversions++;
    if (ctx.baselineR[i] > 0 && rs[i] < 0) reversions++;
  }

  return {
    cell,
    n: all.n,
    wr: all.wr,
    pf: all.pf,
    ev: all.ev,
    net,
    evBuy: buy.ev,
    evSell: sell.ev,
    wrBuy: buy.wr,
    wrSell: sell.wr,
    pfBuy: buy.pf,
    pfSell: sell.pf,
    nBuy: buy.n,
    nSell: sell.n,
    conversions,
    reversions,
    degenerate,
    floorBinds,
    capBinds,
    rs,
  };
}

// ─── stats ──────────────────────────────────────────────────────────────────
function mean(v: number[]): number {
  return v.reduce((a, b) => a + b, 0) / v.length;
}
function sd(v: number[]): number {
  const m = mean(v);
  return Math.sqrt(v.reduce((a, b) => a + (b - m) * (b - m), 0) / (v.length - 1));
}
/** Paired difference vs baseline: same signals, so pairing is valid and tighter. */
function pairedDelta(cellR: number[], baseR: number[]): { d: number; se: number; lo: number; hi: number } {
  const diffs = cellR.map((x, i) => x - baseR[i]);
  const d = mean(diffs);
  const se = sd(diffs) / Math.sqrt(diffs.length);
  return { d, se, lo: d - 1.96 * se, hi: d + 1.96 * se };
}

const sgn = (x: number): string => (x >= 0 ? "+" : "");
const pfs = (x: number): string => (Number.isFinite(x) ? x.toFixed(2) : "inf");

function cellLabel(c: Cell): string {
  const v = c.tp1Mode === "R" ? `${c.tp1Value.toFixed(2)}R` : `${c.tp1Value.toFixed(1)}p`;
  return `TP1=${v.padStart(6)} lock=${c.lock.id.padEnd(13)} tp23=${c.tp23.padEnd(6)}`;
}

// ─── MFE / MAE ──────────────────────────────────────────────────────────────
interface Excursion {
  index: number;
  dir: "BUY" | "SELL";
  status: string;
  mfe24: number;
  mae24: number;
  mfeRes: number;
  maeRes: number;
}

function excursions(ctx: Ctx, canon: Canon[]): Excursion[] {
  const byId = new Map(canon.map((c) => [c.p.id, c]));
  const out: Excursion[] = [];
  for (let i = 0; i < ctx.sigs.length; i++) {
    const p = ctx.sigs[i];
    const c = byId.get(p.id);
    if (!c) continue;
    const stop = Math.abs(p.entry - p.sl);
    const isBuy = p.direction === "BUY";
    const bars = ctx.slices[i];
    const horizon = p.generatedMs + 24 * 60 * 60 * 1000;
    const resEnd = c.resolvedAtBarTs ?? Number.POSITIVE_INFINITY;
    let mfe24 = 0;
    let mae24 = 0;
    let mfeRes = 0;
    let maeRes = 0;
    for (const b of bars) {
      const fav = isBuy ? b.high - p.entry : p.entry - b.low;
      const adv = isBuy ? p.entry - b.low : b.high - p.entry;
      if (b.timestamp <= horizon) {
        if (fav > mfe24) mfe24 = fav;
        if (adv > mae24) mae24 = adv;
      }
      if (b.timestamp <= resEnd) {
        if (fav > mfeRes) mfeRes = fav;
        if (adv > maeRes) maeRes = adv;
      }
      if (b.timestamp > horizon && b.timestamp > resEnd) break;
    }
    out.push({
      index: p.index,
      dir: p.direction,
      status: c.newStatus,
      mfe24: mfe24 / stop,
      mae24: mae24 / stop,
      mfeRes: mfeRes / stop,
      maeRes: maeRes / stop,
    });
  }
  return out;
}

function quantiles(v: number[]): { p10: number; p25: number; p50: number; p75: number; p90: number } {
  const s = [...v].sort((a, b) => a - b);
  const q = (f: number): number => s[Math.min(s.length - 1, Math.floor(f * s.length))];
  return { p10: q(0.1), p25: q(0.25), p50: q(0.5), p75: q(0.75), p90: q(0.9) };
}

// ─── main ───────────────────────────────────────────────────────────────────
const COARSE_R = [0.3, 0.45, 0.6, 0.75, 0.9, 1.0];
const COARSE_P = [15, 22.5, 30, 37.5, 45];
const TP23: Tp23Mode[] = ["abs", "scaled"];

function grid(rVals: number[], pVals: number[]): Cell[] {
  const cells: Cell[] = [];
  for (const lock of LOCKS)
    for (const tp23 of TP23) {
      for (const v of rVals) cells.push({ tp1Mode: "R", tp1Value: v, lock, tp23 });
      for (const v of pVals) cells.push({ tp1Mode: "PIP", tp1Value: v, lock, tp23 });
    }
  return cells;
}

function hr(s: string): void {
  console.log("\n" + "=".repeat(112));
  console.log(s);
  console.log("=".repeat(112));
}

async function main(): Promise<void> {
  hr("ITEM D — TP LADDER SWEEP.  READ-ONLY. NOTHING IMPLEMENTED.");
  console.log(`run at ${new Date().toISOString()}`);

  const { rows: canon, bars, evalNowMs } = await buildCanonical();
  const sigs = parseExport("/tmp/diagnostics_export.txt").filter(
    (p) => p.sl && p.tp1 && p.tp2 && p.tp3 && p.generatedMs && Math.abs(p.entry - p.sl) > 0,
  );

  // pre-slice bars per signal (pure perf; the resolver still applies its own
  // safeBarStart filter, so semantics are untouched)
  const slices = sigs.map((p) => {
    const start = p.generatedMs + 60_000;
    let lo = 0;
    let hi = bars.length;
    while (lo < hi) {
      const mid = (lo + hi) >> 1;
      if (bars[mid].timestamp < start) lo = mid + 1;
      else hi = mid;
    }
    return bars.slice(lo);
  });

  const canonById = new Map(canon.map((c) => [c.p.id, c]));
  const baselineR = sigs.map((p) => canonById.get(p.id)?.r ?? 0);
  const ctx: Ctx = { sigs, slices, evalNowMs, baselineR };

  const baseWins = baselineR.filter((r) => r > 0).length;
  const baseGW = baselineR.filter((r) => r > 0).reduce((a, b) => a + b, 0);
  const baseGL = Math.abs(baselineR.filter((r) => r < 0).reduce((a, b) => a + b, 0));
  const baseEV = mean(baselineR);

  // ══ POWER, STATED BEFORE ANY RESULT ══════════════════════════════════════
  hr("POWER — STATED BEFORE RESULTS (rule 7)");
  const sdR = sd(baselineR);
  const seEV = sdR / Math.sqrt(baselineR.length);
  console.log(`  Every cell re-resolves ALL ${baselineR.length} signals. n = ${baselineR.length} per cell — NOT the n=16`);
  console.log(`  that made Item C unmeasurable. This sweep is adequately powered for the effect sizes at stake.`);
  console.log(`\n  per-signal R: sd = ${sdR.toFixed(4)}R`);
  console.log(`  UNPAIRED SE of a cell's EV        = ${seEV.toFixed(4)}R  (95% half-width +/-${(1.96 * seEV).toFixed(4)}R)`);
  console.log(`  => an EV read in isolation is only resolvable to about +/-${(1.96 * seEV).toFixed(3)}R.`);
  console.log(`  BUT every cell is evaluated on the SAME 369 signals, so cell-vs-baseline is a PAIRED`);
  console.log(`  comparison. Paired SE is reported per cell below and is materially tighter, because the`);
  console.log(`  signal-to-signal variance cancels. All ranking claims use the paired statistic.`);

  hr("CANONICAL BASELINE — STATED ONCE, USED FOR EVERY NUMBER BELOW");
  console.log(`  source     : REAL resolveSignalWithBars, fromScratch:true, evalNowMs = last real bar`);
  console.log(`  predicate  : R > 0     denominator: all ${baselineR.length}`);
  console.log(
    `  BASELINE   : n=${baselineR.length}  WR=${((baseWins / baselineR.length) * 100).toFixed(1)}%  PF=${(baseGW / baseGL).toFixed(2)}  EV=${sgn(baseEV)}${baseEV.toFixed(4)}R  net=${sgn(0)}$${canon.reduce((a, b) => a + b.pnlDollars, 0).toFixed(1)}`,
  );
  const stCount = new Map<string, number>();
  for (const c of canon) stCount.set(c.newStatus, (stCount.get(c.newStatus) ?? 0) + 1);
  console.log(
    `  decomposition: ` +
      [...stCount.entries()].sort((a, b) => b[1] - a[1]).map(([k, v]) => `${k}=${v}`).join("  "),
  );
  console.log(`  (this reproduces EXACTLY after the resolver's ladder hook was added — the hook's`);
  console.log(`   defaults are behaviourally identical to the live code path.)`);

  // ══ COARSE PASS ══════════════════════════════════════════════════════════
  hr("PASS 1 — COARSE GRID (0.15R / 7.5-pip steps, all four discrete axes, no axis dropped)");
  const coarse = grid(COARSE_R, COARSE_P);
  console.log(`  cells: ${coarse.length}   resolutions: ${coarse.length * sigs.length}`);
  const realLog = console.log;
  console.log = () => {};
  const t0 = Date.now();
  const coarseRes = coarse.map((c) => evalCell(c, ctx));
  const coarseMs = Date.now() - t0;
  console.log = realLog;
  console.log(`  completed in ${(coarseMs / 1000).toFixed(1)}s`);

  const surface = (res: CellResult[], mode: Tp1Mode, tp23: Tp23Mode, vals: number[]): void => {
    console.log(`\n  EV per ORIGINAL signal — TP1 as ${mode === "R" ? "R-MULTIPLE" : "ABSOLUTE PIPS"}, TP2/TP3 ${tp23}`);
    console.log(`    ${"TP1".padEnd(8)}` + LOCKS.map((l) => l.id.padStart(14)).join(""));
    for (const v of vals) {
      const label = mode === "R" ? `${v.toFixed(2)}R` : `${v.toFixed(1)}p`;
      const cells = LOCKS.map((l) => {
        const r = res.find(
          (x) => x.cell.tp1Mode === mode && x.cell.tp1Value === v && x.cell.lock.id === l.id && x.cell.tp23 === tp23,
        );
        return r ? `${sgn(r.ev)}${r.ev.toFixed(4)}`.padStart(14) : "".padStart(14);
      });
      console.log(`    ${label.padEnd(8)}` + cells.join(""));
    }
  };

  for (const tp23 of TP23) {
    surface(coarseRes, "R", tp23, COARSE_R);
    surface(coarseRes, "PIP", tp23, COARSE_P);
  }

  const rank = (res: CellResult[]): CellResult[] => [...res].sort((a, b) => b.ev - a.ev);

  const topTable = (res: CellResult[], k: number, title: string): void => {
    console.log(`\n  ${title}`);
    console.log(
      `    ${"cell".padEnd(46)}${"WR".padStart(7)}${"PF".padStart(7)}${"EV".padStart(10)}${"net$".padStart(9)}${"dEV".padStart(10)}${"pairedSE".padStart(10)}${"95% CI".padStart(20)}${"conv".padStart(6)}${"rev".padStart(6)}`,
    );
    console.log("    " + "-".repeat(126));
    for (const r of rank(res).slice(0, k)) {
      const pd = pairedDelta(r.rs, baselineR);
      console.log(
        `    ${cellLabel(r.cell).padEnd(46)}${r.wr.toFixed(1).padStart(6)}%${pfs(r.pf).padStart(7)}` +
          `${(sgn(r.ev) + r.ev.toFixed(4)).padStart(10)}${(sgn(r.net) + r.net.toFixed(0)).padStart(9)}` +
          `${(sgn(pd.d) + pd.d.toFixed(4)).padStart(10)}${pd.se.toFixed(4).padStart(10)}` +
          `${`[${sgn(pd.lo)}${pd.lo.toFixed(4)},${sgn(pd.hi)}${pd.hi.toFixed(4)}]`.padStart(20)}` +
          `${String(r.conversions).padStart(6)}${String(r.reversions).padStart(6)}`,
      );
    }
  };

  topTable(coarseRes, 15, "TOP 15 COARSE CELLS by EV per ORIGINAL signal (dEV = paired delta vs baseline)");

  const coarseBest = rank(coarseRes)[0];
  console.log(`\n  COARSE OPTIMUM: ${cellLabel(coarseBest.cell)}  EV ${sgn(coarseBest.ev)}${coarseBest.ev.toFixed(4)}R`);

  // ══ CAP AXIS ATTRIBUTION ═════════════════════════════════════════════════
  hr("CAP AXIS (0.9 x TP1) — EXPLICIT ATTRIBUTION");
  console.log(`  The cap binds on 36.9% of signals under the LIVE parameterisation because the live lock is`);
  console.log(`  0.35 x STOP while the ceiling is 0.9 x TP1 — two different bases, so the ceiling can bite.`);
  console.log(`  Under a lock expressed as a FRACTION OF TP1 (0.3/0.4/0.5) the ceiling is 0.9 x TP1 and the`);
  console.log(`  lock is at most 0.5 x TP1, so the cap is STRUCTURALLY INERT. Measured, not assumed:\n`);
  console.log(`    ${"lock spec".padEnd(16)}${"cells".padStart(7)}${"mean capBinds/369".padStart(20)}${"mean EV".padStart(11)}${"EV delta cap-on minus cap-off".padStart(32)}`);
  for (const f of [0.3, 0.4, 0.5]) {
    const on = coarseRes.filter((r) => r.cell.lock.id === `TP1x${f.toFixed(1)}`);
    const off = coarseRes.filter((r) => r.cell.lock.id === `TP1x${f.toFixed(1)}/nocap`);
    const d = mean(on.map((r) => r.ev)) - mean(off.map((r) => r.ev));
    console.log(
      `    ${`TP1x${f.toFixed(1)}`.padEnd(16)}${String(on.length).padStart(7)}${mean(on.map((r) => r.capBinds)).toFixed(1).padStart(20)}${(sgn(mean(on.map((r) => r.ev))) + mean(on.map((r) => r.ev)).toFixed(4)).padStart(11)}${(sgn(d) + d.toFixed(6)).padStart(32)}`,
    );
  }
  const rOn = coarseRes.filter((r) => r.cell.lock.id === "R0.35");
  const rOff = coarseRes.filter((r) => r.cell.lock.id === "R0.35/nocap");
  const dR = mean(rOn.map((r) => r.ev)) - mean(rOff.map((r) => r.ev));
  console.log(
    `    ${"R0.35 (live)".padEnd(16)}${String(rOn.length).padStart(7)}${mean(rOn.map((r) => r.capBinds)).toFixed(1).padStart(20)}${(sgn(mean(rOn.map((r) => r.ev))) + mean(rOn.map((r) => r.ev)).toFixed(4)).padStart(11)}${(sgn(dR) + dR.toFixed(6)).padStart(32)}`,
  );
  console.log(`\n  5-pip FLOOR binding (mean signals/369): ` + LOCKS.map((l) => `${l.id}=${mean(coarseRes.filter((r) => r.cell.lock.id === l.id).map((r) => r.floorBinds)).toFixed(1)}`).join("  "));
  console.log(`  DEGENERATE ladders (TP1 at or beyond TP2), mean per cell:`);
  for (const tp23 of TP23)
    for (const mode of ["R", "PIP"] as Tp1Mode[]) {
      const s = coarseRes.filter((r) => r.cell.tp23 === tp23 && r.cell.tp1Mode === mode);
      console.log(`    tp23=${tp23.padEnd(7)} TP1 as ${mode.padEnd(4)}  mean=${mean(s.map((r) => r.degenerate)).toFixed(1)}  max=${Math.max(...s.map((r) => r.degenerate))}`);
    }

  // ══ FINE PASS ════════════════════════════════════════════════════════════
  hr("PASS 2 — FINE GRID (+/- 2 coarse steps around the coarse optimum, full 0.05R / 2.5-pip resolution)");
  const bestR = rank(coarseRes.filter((r) => r.cell.tp1Mode === "R"))[0];
  const bestP = rank(coarseRes.filter((r) => r.cell.tp1Mode === "PIP"))[0];
  console.log(`  coarse optimum, R-parameterisation  : ${cellLabel(bestR.cell)}  EV ${sgn(bestR.ev)}${bestR.ev.toFixed(4)}R`);
  console.log(`  coarse optimum, PIP-parameterisation: ${cellLabel(bestP.cell)}  EV ${sgn(bestP.ev)}${bestP.ev.toFixed(4)}R`);

  const fineR: number[] = [];
  for (let v = Math.max(0.3, bestR.cell.tp1Value - 0.3); v <= Math.min(1.0, bestR.cell.tp1Value + 0.3) + 1e-9; v += 0.05)
    fineR.push(Number(v.toFixed(2)));
  const fineP: number[] = [];
  for (let v = Math.max(15, bestP.cell.tp1Value - 15); v <= Math.min(45, bestP.cell.tp1Value + 15) + 1e-9; v += 2.5)
    fineP.push(Number(v.toFixed(1)));
  console.log(`  fine TP1 R values  : ${fineR.join(", ")}`);
  console.log(`  fine TP1 pip values: ${fineP.join(", ")}`);

  const fine = grid(fineR, fineP);
  console.log(`  cells: ${fine.length}   resolutions: ${fine.length * sigs.length}`);
  console.log = () => {};
  const t1 = Date.now();
  const fineRes = fine.map((c) => evalCell(c, ctx));
  const fineMs = Date.now() - t1;
  console.log = realLog;
  console.log(`  completed in ${(fineMs / 1000).toFixed(1)}s`);

  for (const tp23 of TP23) {
    surface(fineRes, "R", tp23, fineR);
    surface(fineRes, "PIP", tp23, fineP);
  }
  topTable(fineRes, 20, "TOP 20 FINE CELLS by EV per ORIGINAL signal");

  const best = rank(fineRes)[0];
  const bestPd = pairedDelta(best.rs, baselineR);

  hr("FINE OPTIMUM — FULL METRICS");
  console.log(`  cell: ${cellLabel(best.cell)}`);
  console.log(
    `    POOLED  n=${best.n}  WR=${best.wr.toFixed(1)}%  PF=${pfs(best.pf)}  EV=${sgn(best.ev)}${best.ev.toFixed(4)}R  net=${sgn(best.net)}$${best.net.toFixed(1)}`,
  );
  console.log(`    BUY     n=${best.nBuy}  WR=${best.wrBuy.toFixed(1)}%  PF=${pfs(best.pfBuy)}  EV=${sgn(best.evBuy)}${best.evBuy.toFixed(4)}R`);
  console.log(`    SELL    n=${best.nSell}  WR=${best.wrSell.toFixed(1)}%  PF=${pfs(best.pfSell)}  EV=${sgn(best.evSell)}${best.evSell.toFixed(4)}R`);
  console.log(
    `    vs baseline: dEV ${sgn(bestPd.d)}${bestPd.d.toFixed(4)}R  paired SE ${bestPd.se.toFixed(4)}  95% CI [${sgn(bestPd.lo)}${bestPd.lo.toFixed(4)}, ${sgn(bestPd.hi)}${bestPd.hi.toFixed(4)}]  ` +
      `${bestPd.lo > 0 ? "EXCLUDES ZERO" : "INCLUDES ZERO — not distinguishable from no change"}`,
  );
  console.log(`    full-loss -> locked-win conversions vs current ladder: ${best.conversions}   reversions (win -> full loss): ${best.reversions}   net ${sgn(best.conversions - best.reversions)}${best.conversions - best.reversions}`);

  // ══ PLATEAU ══════════════════════════════════════════════════════════════
  hr("PLATEAU CHECK (mandatory, pre-registered: every +/-1-step neighbour within 20% of the optimum's EV)");
  const fineVals = best.cell.tp1Mode === "R" ? fineR : fineP;
  const vi = fineVals.indexOf(best.cell.tp1Value);
  const lockFam = LOCKS.filter((l) => l.family === best.cell.lock.family && l.cap === best.cell.lock.cap).sort(
    (a, b) => a.value - b.value,
  );
  const li = lockFam.findIndex((l) => l.id === best.cell.lock.id);

  interface Nb {
    what: string;
    cell: Cell | null;
  }
  const nbs: Nb[] = [];
  for (const d of [-1, 1]) {
    const j = vi + d;
    nbs.push({
      what: `TP1 ${d > 0 ? "+" : "-"}1 step`,
      cell: j >= 0 && j < fineVals.length ? { ...best.cell, tp1Value: fineVals[j] } : null,
    });
  }
  for (const d of [-1, 1]) {
    const j = li + d;
    nbs.push({
      what: `lock ${d > 0 ? "+" : "-"}1 step`,
      cell: j >= 0 && j < lockFam.length ? { ...best.cell, lock: lockFam[j] } : null,
    });
  }
  nbs.push({
    what: "cap toggled",
    cell: (() => {
      const alt = LOCKS.find((l) => l.family === best.cell.lock.family && l.value === best.cell.lock.value && l.cap !== best.cell.lock.cap);
      return alt ? { ...best.cell, lock: alt } : null;
    })(),
  });
  nbs.push({ what: "tp23 toggled", cell: { ...best.cell, tp23: best.cell.tp23 === "abs" ? "scaled" : "abs" } });

  const thresh = Math.abs(best.ev) * 0.2;
  console.log(`  optimum EV ${sgn(best.ev)}${best.ev.toFixed(4)}R   20% band = EV must stay within +/-${thresh.toFixed(4)}R  =>  >= ${(best.ev - thresh).toFixed(4)}R\n`);
  console.log(`    ${"neighbour".padEnd(18)}${"cell".padEnd(46)}${"EV".padStart(10)}${"drop".padStart(10)}${"verdict".padStart(12)}`);
  let plateau = true;
  let checked = 0;
  for (const nb of nbs) {
    if (!nb.cell) {
      console.log(`    ${nb.what.padEnd(18)}${"(grid edge — no neighbour)".padEnd(46)}`);
      continue;
    }
    const c = nb.cell;
    const r =
      fineRes.find(
        (x) =>
          x.cell.tp1Mode === c.tp1Mode &&
          x.cell.tp1Value === c.tp1Value &&
          x.cell.lock.id === c.lock.id &&
          x.cell.tp23 === c.tp23,
      ) ?? evalCell(c, ctx);
    const drop = best.ev - r.ev;
    const ok = drop <= thresh;
    if (!ok) plateau = false;
    checked++;
    console.log(
      `    ${nb.what.padEnd(18)}${cellLabel(c).padEnd(46)}${(sgn(r.ev) + r.ev.toFixed(4)).padStart(10)}${(sgn(-drop) + (-drop).toFixed(4)).padStart(10)}${(ok ? "within" : "OUTSIDE").padStart(12)}`,
    );
  }
  console.log(`\n  PLATEAU VERDICT: ${plateau ? "PASS" : "FAIL"} — ${checked} neighbours checked; ${plateau ? "the optimum sits on a plateau" : "at least one neighbour falls >20% away: this is a SPIKE and is REJECTED per the pre-registered criterion"}`);

  // ══ STABILITY ════════════════════════════════════════════════════════════
  hr("STABILITY CHECK (mandatory, pre-registered: chronological half-split, each half optimised independently)");
  const order = sigs.map((p, i) => ({ i, t: p.generatedMs })).sort((a, b) => a.t - b.t);
  const half = Math.floor(order.length / 2);
  const firstIdx = new Set(order.slice(0, half).map((x) => x.i));
  const iso = (ms: number): string => new Date(ms).toISOString().replace(".000Z", "Z");
  console.log(`  H1: n=${half}  ${iso(order[0].t)} -> ${iso(order[half - 1].t)}`);
  console.log(`  H2: n=${order.length - half}  ${iso(order[half].t)} -> ${iso(order[order.length - 1].t)}`);

  const halfEv = (r: CellResult, first: boolean): number => {
    const v = r.rs.filter((_, i) => firstIdx.has(i) === first);
    return mean(v);
  };
  for (const [lbl, first] of [
    ["H1 (earlier half)", true],
    ["H2 (later half)", false],
  ] as [string, boolean][]) {
    const ranked = [...fineRes].sort((a, b) => halfEv(b, first) - halfEv(a, first));
    console.log(`\n  ${lbl} — top 5 independently optimised:`);
    for (const r of ranked.slice(0, 5))
      console.log(`    ${cellLabel(r.cell).padEnd(46)}EV=${(sgn(halfEv(r, first)) + halfEv(r, first).toFixed(4)).padStart(10)}`);
    const b = ranked[0];
    console.log(`    => ${lbl} optimum: ${cellLabel(b.cell)}`);
    console.log(`       pooled optimum evaluated on this half: EV ${sgn(halfEv(best, first))}${halfEv(best, first).toFixed(4)}R`);
  }
  const h1Best = [...fineRes].sort((a, b) => halfEv(b, true) - halfEv(a, true))[0];
  const h2Best = [...fineRes].sort((a, b) => halfEv(b, false) - halfEv(a, false))[0];
  console.log(`\n  H1 optimum TP1 = ${h1Best.cell.tp1Mode === "R" ? h1Best.cell.tp1Value + "R" : h1Best.cell.tp1Value + "p"}  lock=${h1Best.cell.lock.id}  tp23=${h1Best.cell.tp23}`);
  console.log(`  H2 optimum TP1 = ${h2Best.cell.tp1Mode === "R" ? h2Best.cell.tp1Value + "R" : h2Best.cell.tp1Value + "p"}  lock=${h2Best.cell.lock.id}  tp23=${h2Best.cell.tp23}`);

  // ══ PER-DIRECTION ════════════════════════════════════════════════════════
  hr("PER-DIRECTION OPTIMA — reported, not forced into one ladder");
  for (const [lbl, key] of [
    ["BUY", "evBuy"],
    ["SELL", "evSell"],
  ] as [string, "evBuy" | "evSell"][]) {
    const ranked = [...fineRes].sort((a, b) => b[key] - a[key]);
    console.log(`\n  ${lbl} — top 5:`);
    for (const r of ranked.slice(0, 5))
      console.log(
        `    ${cellLabel(r.cell).padEnd(46)}EV=${(sgn(r[key]) + r[key].toFixed(4)).padStart(10)}  WR=${(lbl === "BUY" ? r.wrBuy : r.wrSell).toFixed(1)}%  PF=${pfs(lbl === "BUY" ? r.pfBuy : r.pfSell)}`,
      );
    console.log(`    pooled optimum on ${lbl}: EV ${sgn(best[key])}${best[key].toFixed(4)}R`);
  }

  // ══ MFE / MAE ════════════════════════════════════════════════════════════
  hr("MFE / MAE — DIAGNOSTIC CONTEXT AND THE TRANSFER PROPERTY");
  const exc = excursions(ctx, canon);
  console.log(`  Both measured in R (multiples of the signal's own realised stop distance).`);
  console.log(`  mfe24/mae24 use a FIXED 24h horizon and are therefore LADDER-INDEPENDENT — this is the`);
  console.log(`  statistic to compare post-F signals against. mfeRes/maeRes use each signal's actual`);
  console.log(`  resolution window and ARE endogenous to the current ladder.\n`);
  const grp = (name: string, set: Excursion[]): void => {
    if (!set.length) return;
    const f = quantiles(set.map((e) => e.mfe24));
    const a = quantiles(set.map((e) => e.mae24));
    console.log(
      `    ${name.padEnd(22)}n=${String(set.length).padStart(3)}   MFE24 p10/25/50/75/90 = ${f.p10.toFixed(2)}/${f.p25.toFixed(2)}/${f.p50.toFixed(2)}/${f.p75.toFixed(2)}/${f.p90.toFixed(2)}   MAE24 = ${a.p10.toFixed(2)}/${a.p25.toFixed(2)}/${a.p50.toFixed(2)}/${a.p75.toFixed(2)}/${a.p90.toFixed(2)}`,
    );
  };
  grp("ALL", exc);
  grp("BUY", exc.filter((e) => e.dir === "BUY"));
  grp("SELL", exc.filter((e) => e.dir === "SELL"));
  console.log("");
  for (const st of ["SL_HIT", "SL_AFTER_BE", "ALL_TARGETS_HIT", "PARTIAL_WIN_SL_HIT"])
    grp(st, exc.filter((e) => e.status === st));
  console.log("");
  const slh = exc.filter((e) => e.status === "SL_HIT");
  for (const t of [0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]) {
    const reach = slh.filter((e) => e.mfe24 >= t).length;
    console.log(
      `    of the ${slh.length} current full losses, ${String(reach).padStart(3)} (${((reach / slh.length) * 100).toFixed(1)}%) reached +${t.toFixed(2)}R favourable within 24h — i.e. a TP1 at ${t.toFixed(2)}R would have armed the lock`,
    );
  }

  // ══ CSV ══════════════════════════════════════════════════════════════════
  const csv = [
    "pass,tp1Mode,tp1Value,lock,cap,tp23,n,wr,pf,ev,net,evBuy,evSell,wrBuy,wrSell,conversions,reversions,degenerate,floorBinds,capBinds",
    ...[...coarseRes.map((r) => ["coarse", r] as const), ...fineRes.map((r) => ["fine", r] as const)].map(([pass, r]) =>
      [
        pass,
        r.cell.tp1Mode,
        r.cell.tp1Value,
        r.cell.lock.family === "fracTP1" ? `TP1x${r.cell.lock.value}` : `R${r.cell.lock.value}`,
        r.cell.lock.cap,
        r.cell.tp23,
        r.n,
        r.wr.toFixed(2),
        Number.isFinite(r.pf) ? r.pf.toFixed(4) : "inf",
        r.ev.toFixed(6),
        r.net.toFixed(2),
        r.evBuy.toFixed(6),
        r.evSell.toFixed(6),
        r.wrBuy.toFixed(2),
        r.wrSell.toFixed(2),
        r.conversions,
        r.reversions,
        r.degenerate,
        r.floorBinds,
        r.capBinds,
      ].join(","),
    ),
  ].join("\n");
  writeFileSync("/tmp/itemD_surface.csv", csv);
  console.log(`\n  full surface written to /tmp/itemD_surface.csv (${coarseRes.length + fineRes.length} cells)`);

  hr("END — NOTHING WAS IMPLEMENTED. The ladder decision is the user's.");
  void LOCK_BY_ID;
}

if (import.meta.main) {
  main().catch((e) => {
    console.error("Fatal:", e);
    process.exit(1);
  });
}
