/**
 * ITEM 57 — REAL-BAR REPLAY HARNESS.
 *
 * The standing instrument for any future "how many signals before vs after?"
 * question. Replays the REAL engine over REAL `gold_m1_bars` via the existing
 * `__injectBarSeriesForTestOnly` hook.
 *
 * WHY THIS EXISTS. `runSignalSimulation.ts` was disqualified in Item 53: it drives
 * the engine from `generateSyntheticPrice()` with base 3034.5 while live gold is
 * ~4250. Every price-scale-dependent gate (zone width, bounce threshold, the
 * absolute-dollar ATR regime constants) is unmeasurable on that tape. This harness
 * replaces the synthetic generator with the real one, and nothing else.
 *
 * HOW IT WORKS.
 *   1. `buildSandboxEngine()` transforms `services/signalEngine.ts` into a
 *      Node-runnable module: the `react-native` import (Flow-typed, unparseable by
 *      bun/node) and the AsyncStorage / trpc / learning-store imports are replaced
 *      with in-memory stubs. This is the same transform the __sandbox_item44__ /
 *      __sandbox_item45__ copies used, but GENERATED from the live file at run time
 *      rather than hand-copied — so the harness can never silently drift from the
 *      shipped engine the way a stale hand-copy would.
 *   2. Real M1 bars are paged from Supabase via the anon key (DATA-SOURCE RULE).
 *   3. Bars are injected with `__injectBarSeriesForTestOnly`, then the engine is
 *      stepped forward bar by bar with the real close as the external price.
 *   4. Emissions and rejection reasons are captured off the engine's own console
 *      output and template-aggregated (variable numbers collapsed to `<N>`) so the
 *      breakdown is stable across runs.
 *
 * USAGE:
 *   bun scripts/item57_realbar_replay_harness.ts            # replay, print breakdown
 *   bun scripts/item57_realbar_replay_harness.ts --label X  # tag the run for A/B
 *
 * READ-ONLY against Supabase.
 */

import { createClient } from '@supabase/supabase-js';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

interface Bar {
  timestamp: number;
  open: number;
  high: number;
  low: number;
  close: number;
}

const loadEnv = (): Record<string, string> => {
  const env: Record<string, string> = {};
  try {
    for (const line of readFileSync('.env', 'utf-8').split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eq = trimmed.indexOf('=');
      if (eq < 0) continue;
      env[trimmed.slice(0, eq)] = trimmed.slice(eq + 1).replace(/^["']|["']$/g, '');
    }
  } catch {
    // fall through
  }
  return env;
};

const SANDBOX_DIR = 'scripts/__sandbox_item57__';
const SANDBOX_FILE = join(SANDBOX_DIR, 'signalEngine.replay.ts');

/**
 * Rewrite the live engine into a Node-runnable module.
 * Only IMPORTS are stubbed. No engine logic is altered — that is the whole point:
 * the harness must measure the shipped engine, not a fork of it.
 */
function buildSandboxEngine(): string {
  const src = readFileSync('services/signalEngine.ts', 'utf-8');
  const lines = src.split('\n');

  // ITEM 84 — `--tier0-dark` stubs the TIER_0 zone read so the engine runs with NO
  // server zones. `fetchTier0SRZones` is otherwise NOT stubbed: the replay reads the
  // live `sr_zones_v1` table, which is why the armed arm is a genuine armed arm.
  // Item 84 asks whether the FIXED 0.55 conviction threshold is materially stricter
  // when the zone layer works than when it is dark — i.e. whether the engine emits
  // MORE when its zone layer is broken. That requires a dark arm that is dark for
  // one reason only.
  const tier0Dark = process.argv.includes('--tier0-dark');

  const stubs = [
    '// AUTO-GENERATED by item57_realbar_replay_harness.ts. Do not edit.',
    '// Imports are stubbed for Node; ALL engine logic below is byte-identical to',
    '// services/signalEngine.ts as shipped.',
    'const sandboxStorage = new Map<string, string>();',
    'const AsyncStorage = {',
    '  async getItem(key: string): Promise<string | null> { return sandboxStorage.get(key) ?? null; },',
    '  async setItem(key: string, value: string): Promise<void> { sandboxStorage.set(key, value); },',
    '  async removeItem(key: string): Promise<void> { sandboxStorage.delete(key); },',
    '};',
    'const Platform = { OS: "web" as const };',
    'const trpcClient = {} as never;',
    'async function fetchHistoricalData(): Promise<never[]> { return []; }',
    'async function appendOutcomeToStore(): Promise<void> {}',
    'async function getAllOutcomesFromStore(): Promise<unknown[]> { return []; }',
    'async function getOutcomeCountFromStore(): Promise<number> { return 0; }',
    'async function pruneOutcomeStoreToCap(): Promise<void> {}',
    'async function migrateLegacyOutcomesIfEmpty(): Promise<number> { return 0; }',
    'async function pushOutcomesToRemote(): Promise<{ upserted: number; queued: number; failed: number; failureDetail: string | null }> { return { upserted: 0, queued: 0, failed: 0, failureDetail: null }; }',
    'async function hydrateLearningStoreFromRemote(): Promise<unknown> { return { available: false }; }',
    'function getLearningCorpusStats(): { hydrateUnavailableCount: number } { return { hydrateUnavailableCount: 0 }; }',
    'type StoredTradeOutcome = Record<string, unknown>;',
    'async function appendDiagnosticEvent(): Promise<void> {}',
    'async function pushShadowSellRecord(): Promise<void> {}',
    'async function pushEmittedSignalRecord(): Promise<void> {}',
    'type ShadowSellRecord = Record<string, unknown>;',
    ...(tier0Dark
      ? [
          '// ITEM 84 dark arm: TIER_0 server zones forced unavailable.',
          'async function fetchTier0SRZones(): Promise<null> { return null; }',
          'function recordTier0FallbackUse(): void {}',
        ]
      : []),
    '',
    '// A11: seed production model weights so getFeatureModulation returns the LIVE',
    '// value (rsi_weight=-1.0 -> modulation=0) instead of the cold-start 1.0.',
    'sandboxStorage.set("model_weights_v1", JSON.stringify({ weights: [["rsi_weight",-1.0],["sentiment_weight",-0.473823],["atr_weight",0.225086],["timeWindow_weight",-0.09845],["volume_weight",0.082048],["dxy_weight",0.0]], lastTrainingTime: Date.parse("2026-08-11T12:06:34Z"), corpusSizeAtTraining: 53, hydrateUnavailableAtTraining: 0 }));',
    '',
  ];

  // Drop the import statements that pull in React Native / storage / network.
  const dropPrefixes = [
    ...(tier0Dark ? ['import { fetchTier0SRZones'] : []),
    'import AsyncStorage from',
    'import { Platform } from "react-native"',
    'import { fetchHistoricalData, trpcClient } from',
    'import { appendOutcome as appendOutcomeToStore',
    'import { appendDiagnosticEvent } from',
    'import { pushShadowSellRecord',
    'import { pushEmittedSignalRecord } from',
  ];

  const kept: string[] = [];
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    const matched = dropPrefixes.some((p) => line.startsWith(p));
    if (matched) {
      // Consume the whole (possibly multi-line) import statement.
      let stmt = line;
      while (!stmt.includes('";') && !stmt.trimEnd().endsWith('"') && i + 1 < lines.length) {
        i += 1;
        stmt += lines[i];
      }
      i += 1;
      continue;
    }
    kept.push(line);
    i += 1;
  }

  // Rewrite the `@/` alias to relative paths so Node resolves them.
  const body = kept.join('\n').replace(/from "@\//g, 'from "../../').replace(/from '@\//g, "from '../../");

  return `${stubs.join('\n')}\n${body}\n`;
}

const pct = (n: number, d: number): string => (d === 0 ? 'n/a' : `${((n / d) * 100).toFixed(1)}%`);

/** Collapse variable numbers so rejection reasons aggregate into stable templates. */
const templatize = (msg: string): string =>
  msg
    .replace(/-?\d+\.\d+/g, '<N>')
    .replace(/\b\d+\b/g, '<N>')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 120);

/**
 * ITEM 82 / B1 — THE SETTINGS ARGUMENT.
 *
 * F-0. This harness used to call `engine.generateSignal()` with NO arguments.
 * `settings` has no default in the engine signature (signalEngine.ts:7230-7233),
 * so the first dereference — `settings.allowShortSignals` at signalEngine.ts:7387
 * (the PHASE B2 stand-aside gate) — threw a TypeError on EVERY evaluation. The
 * bare `catch {}` in the replay loop swallowed it and counted it as an attempt,
 * so every run this instrument ever produced measured the engine only as far as
 * the conviction gate, and reported `emissions: 0` as though that were a finding.
 * It was an artifact of the harness, not a property of the engine.
 *
 * Every value below is sourced field-by-field from the PRODUCTION defaults so a
 * replay measures what production runs, not a harness-invented configuration.
 */
interface ReplaySettings {
  tp1Pips: number;
  tp2Pips: number;
  tp3Pips: number;
  slPips: number;
  numberOfTPs: number;
  minConfidence: number;
  enableNotifications: boolean;
  enableTelegramNotifier: boolean;
  basePositionSize: number;
  maxRiskPercentage: number;
  useKellyCriterion: boolean;
  useDynamicSL: boolean;
  maxSLPips: number;
  allowShortSignals: boolean;
}

/** Sourced from contexts/TradingContext.tsx DEFAULT_SETTINGS, field by field. */
const PRODUCTION_SETTINGS: ReplaySettings = {
  tp1Pips: 49,               // contexts/TradingContext.tsx:43
  tp2Pips: 74,               // contexts/TradingContext.tsx:44
  tp3Pips: 98,               // contexts/TradingContext.tsx:45
  slPips: 70,                // contexts/TradingContext.tsx:46
  numberOfTPs: 3,            // contexts/TradingContext.tsx:47
  minConfidence: 0.68,       // contexts/TradingContext.tsx:48
  enableNotifications: true, // contexts/TradingContext.tsx:49
  enableTelegramNotifier: true, // contexts/TradingContext.tsx:50
  basePositionSize: 0.01,    // contexts/TradingContext.tsx:51
  maxRiskPercentage: 2.0,    // contexts/TradingContext.tsx:52
  useKellyCriterion: true,   // contexts/TradingContext.tsx:53
  useDynamicSL: false,       // contexts/TradingContext.tsx:54 (B7: Item 19 measured dynamic SL worse)
  maxSLPips: 90,             // contexts/TradingContext.tsx:55
  allowShortSignals: false,  // contexts/TradingContext.tsx:56
};

/**
 * `--settings-override key=value,key=value` — lets a single toggle vary between
 * the arms of an A/B pair without editing the harness (editing it would make the
 * arms non-comparable by construction). An unknown key is a HARD STOP, not a
 * silent no-op: a typo'd override that quietly did nothing would produce two
 * byte-identical arms and they would be reported as a measured difference.
 */
function buildReplaySettings(): ReplaySettings {
  const settings: ReplaySettings = { ...PRODUCTION_SETTINGS };
  const idx = process.argv.indexOf('--settings-override');
  const raw = idx >= 0 ? (process.argv[idx + 1] ?? '') : '';
  const applied: string[] = [];
  if (raw) {
    for (const pair of raw.split(',')) {
      const eq = pair.indexOf('=');
      if (eq < 0) {
        console.error(`BLOCKER: malformed --settings-override entry "${pair}" (expected key=value)`);
        process.exit(2);
      }
      const key = pair.slice(0, eq).trim();
      const value = pair.slice(eq + 1).trim();
      if (!(key in settings)) {
        console.error(`BLOCKER: --settings-override key "${key}" is not a Settings field. Refusing to run.`);
        process.exit(2);
      }
      const record = settings as unknown as Record<string, unknown>;
      if (typeof record[key] === 'boolean') {
        if (value !== 'true' && value !== 'false') {
          console.error(`BLOCKER: --settings-override ${key} expects true|false, got "${value}"`);
          process.exit(2);
        }
        record[key] = value === 'true';
      } else {
        const n = Number(value);
        if (!Number.isFinite(n)) {
          console.error(`BLOCKER: --settings-override ${key} expects a number, got "${value}"`);
          process.exit(2);
        }
        record[key] = n;
      }
      applied.push(`${key}=${value}`);
    }
  }
  console.log('  settings: PRODUCTION defaults from contexts/TradingContext.tsx:43-56');
  console.log(`    ${JSON.stringify(settings)}`);
  console.log(`  settings overrides applied: ${applied.length === 0 ? '(none)' : applied.join(', ')}`);
  return settings;
}

async function main(): Promise<void> {
  const label = process.argv.includes('--label')
    ? process.argv[process.argv.indexOf('--label') + 1]
    : 'unlabelled';

  const line = '='.repeat(84);
  console.log(`\n${line}`);
  console.log(`ITEM 57 — REAL-BAR REPLAY HARNESS  [run: ${label}]`);
  console.log(line);

  // ── 1. Generate the sandbox engine from the LIVE file ──────────────────────
  mkdirSync(SANDBOX_DIR, { recursive: true });
  const generated = buildSandboxEngine();
  writeFileSync(SANDBOX_FILE, generated, 'utf-8');
  console.log(`  sandbox engine generated: ${SANDBOX_FILE} (${generated.split('\n').length} lines)`);

  // ── 2. Load real bars ──────────────────────────────────────────────────────
  const env = loadEnv();
  const url = env.EXPO_PUBLIC_SUPABASE_URL ?? process.env.EXPO_PUBLIC_SUPABASE_URL;
  const anon = env.EXPO_PUBLIC_SUPABASE_ANON_KEY ?? process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY;
  if (!url || !anon) {
    console.error('Missing Supabase credentials');
    process.exit(1);
  }
  const client = createClient(url, anon, { auth: { autoRefreshToken: false, persistSession: false } });

  // ITEM 72 — TAPE PINNING. The window used to be computed from the real clock at load
  // time, so two runs launched 20 minutes apart loaded slightly different bar sets
  // (13,899 vs 13,849 bars) and were therefore never strictly comparable. `--tape-end`
  // pins the window's end to a fixed epoch ms; a before/after pair MUST pass the same
  // value. Without it the harness still runs, but only same-minute runs are comparable.
  const tapeEndArgIdx = process.argv.indexOf('--tape-end');
  const tapeEndParsed = tapeEndArgIdx >= 0 ? Number(process.argv[tapeEndArgIdx + 1]) : NaN;
  const tapeEnd = Number.isFinite(tapeEndParsed) && tapeEndParsed > 0 ? tapeEndParsed : Date.now();
  console.log(`  tape end pinned at: ${new Date(tapeEnd).toISOString()}${tapeEndArgIdx >= 0 ? ' (--tape-end)' : ' (UNPINNED — real clock)'}`);

  const since = new Date(tapeEnd - 14 * 24 * 60 * 60 * 1000).toISOString();
  const m1: Bar[] = [];
  for (let from = 0; ; from += 1000) {
    const { data, error } = await client
      .from('gold_m1_bars')
      .select('timestamp, open, high, low, close')
      .gte('timestamp', since)
      .order('timestamp', { ascending: true })
      .range(from, from + 999);
    if (error) {
      console.error('bar fetch failed:', error.message);
      process.exit(1);
    }
    const rows = (data ?? []) as { timestamp: string; open: number; high: number; low: number; close: number }[];
    m1.push(...rows.map((r) => ({
      timestamp: new Date(r.timestamp).getTime(),
      open: Number(r.open),
      high: Number(r.high),
      low: Number(r.low),
      close: Number(r.close),
    })));
    if (rows.length < 1000) break;
  }
  // Trim to the pinned end so a later run cannot pick up bars ingested in the meantime.
  while (m1.length > 0 && m1[m1.length - 1].timestamp > tapeEnd) m1.pop();

  // CORRECTION 15 — ZONE BATCH STAMP. `fetchTier0SRZones` is NOT stubbed in the
  // sandbox: the replay reads the LIVE `sr_zones_v1` table. If that table is
  // refreshed between two arms, the arms saw different zones and the comparison is
  // confounded regardless of how carefully window and step were matched. Stamping
  // the batch before AND after each arm makes that confound observable instead of
  // invisible.
  const stampZoneBatch = async (phase: string): Promise<void> => {
    const { data, error } = await client
      .from('sr_zones_v1')
      .select('updated_at')
      .order('updated_at', { ascending: false })
      .limit(1);
    if (error) {
      console.log(`  ZONE BATCH STAMP (${phase}): read failed — ${error.message}`);
      return;
    }
    const rows = (data ?? []) as { updated_at: string }[];
    const { count } = await client.from('sr_zones_v1').select('*', { count: 'exact', head: true });
    console.log(`  ZONE BATCH STAMP (${phase}): max updated_at=${rows[0]?.updated_at ?? 'EMPTY'} rows=${count ?? 'n/a'}`);
  };
  await stampZoneBatch('before replay');
  console.log(`  real M1 bars loaded: ${m1.length}`);
  console.log(`  window: ${new Date(m1[0].timestamp).toISOString()} -> ${new Date(m1[m1.length - 1].timestamp).toISOString()}`);
  console.log(`  price range: $${Math.min(...m1.map((b) => b.low)).toFixed(2)} .. $${Math.max(...m1.map((b) => b.high)).toFixed(2)}`);
  console.log('  (contrast: runSignalSimulation.ts base price 3034.5 — off by ~$1,200)');

  // ── REPLAY CLOCK ──────────────────────────────────────────────────────────
  // The engine refuses to serve a bar series older than BAR_MAX_AGE_M5_MS, judged
  // against Date.now(). Historical bars are by definition old in wall-clock terms,
  // so an un-clocked replay measures nothing but the staleness guard: the first run
  // of this harness returned 2731/2733 = 99.9% "directional bar layer unavailable or
  // stale" and 0 emissions. That is a property of the harness, not of the engine.
  //
  // The fix is to advance a REPLAY CLOCK with the tape: while stepping, Date.now()
  // returns the timestamp of the most recently injected bar. The staleness guard is
  // left fully armed and unmodified — it is simply asked "is this bar fresh AS OF the
  // moment it was the latest bar?", which is the question it answers in production.
  //
  // ITEM 72 — DETERMINISM. Stubbing `Date.now()` alone is NOT sufficient, and that
  // insufficiency is what produced the ~4pp same-code noise floor (172 vs 183 conviction
  // rejections on byte-identical engines). Two distinct causes were found:
  //
  //   (1) The engine reads wall-clock time through the `new Date()` CONSTRUCTOR as well
  //       as through `Date.now()`. Session classification, the low-liquidity window, the
  //       hard dead-hour clock blocks and the daily market-close break all call
  //       `new Date().getUTCHours()` — signalEngine.ts:3372, 4013, 4038, 4307, 4557,
  //       6727, 7219, 7486, 8988 among others. Those read the REAL hour, so a replay
  //       executed at 06:00 UTC classified the very same bar into a different session
  //       than one executed at 12:00 UTC. Fixed by patching the Date CONSTRUCTOR so a
  //       zero-argument `new Date()` returns the replay instant, while every explicit
  //       `new Date(x)` is forwarded untouched.
  //   (2) The clock must be installed BEFORE the engine module is imported. Module-level
  //       initialisers in the engine capture time at import (fetch throttles, series
  //       build stamps), so a clock installed after the import left those captures on the
  //       real clock and they varied run to run.
  //
  // Same boundary and same spirit as `__injectBarSeriesForTestOnly`: replay-time injection
  // only, no engine logic altered. The clock gates stay fully armed — they are simply
  // asked about the moment the bar was current, which is what they answer in production.
  const RealDate = Date;
  const realDateNow = Date.now;
  let replayNow = m1[0].timestamp;
  class ReplayDate extends RealDate {
    constructor(...args: unknown[]) {
      if (args.length === 0) {
        super(replayNow);
        return;
      }
      // @ts-expect-error — forward the real Date overloads verbatim.
      super(...args);
    }
    static now(): number {
      return replayNow;
    }
  }
  // eslint-disable-next-line no-global-assign
  (globalThis as unknown as { Date: unknown }).Date = ReplayDate;
  Date.now = (): number => replayNow;

  // ── 3. Load the engine (AFTER the clock is installed — see cause (2) above) ─
  let engineModule: Record<string, unknown>;
  try {
    engineModule = (await import(`../${SANDBOX_FILE}`)) as Record<string, unknown>;
  } catch (err) {
    console.error(`\n${line}`);
    console.error('BLOCKER — sandbox engine could not be loaded. Reporting nothing as done.');
    console.error(line);
    console.error(`  ${err instanceof Error ? err.message : String(err)}`);
    console.error('  The transform above stubs imports only. If this fails, the engine has');
    console.error('  acquired a new module-level dependency that the stub list does not cover;');
    console.error('  add it to `stubs` / `dropPrefixes` rather than editing engine logic.');
    process.exit(2);
  }

  const engine = engineModule.signalEngine as {
    __injectBarSeriesForTestOnly?: (m1: readonly Bar[]) => void;
    generateSignal: (...args: unknown[]) => Promise<unknown>;
  };
  if (!engine || typeof engine.__injectBarSeriesForTestOnly !== 'function') {
    console.error('BLOCKER: __injectBarSeriesForTestOnly not present on the engine export.');
    process.exit(2);
  }
  const setExternalPrice = engineModule.setExternalPrice as ((p: number, s: string) => void) | undefined;
  console.log('  engine loaded, injection hook present.');

  // A11/A12/A14: harness flags must be declared BEFORE the seed-weights block below.
  //
  // CORRECTION 15 — `--seed-weights` is now an EXPLICIT ARM SELECTOR, not a one-off
  // probe. The prior round ran the seeded arm over a 15-hour window at step 3 and
  // compared its rate against an UNSEEDED arm over the full tape at step 25, then
  // attributed the difference to modulation. Window, step and sample size all
  // differed, so that comparison established nothing. The two arms must now differ
  // in the weight seed and NOTHING else, and the harness prints the arm identity
  // plus the zone-batch stamp so a reader can verify they were comparable.
  const seedWeights = process.argv.includes('--seed-weights');
  const perAttempt = process.argv.includes('--per-attempt');
  const windowStartIdx = process.argv.indexOf('--window-start');
  const windowStart = windowStartIdx >= 0 ? Number(process.argv[windowStartIdx + 1]) : 0;
  console.log(`  ARM: ${seedWeights ? 'MODULATED (production weights seeded, rsi modulation -> 0)' : 'UNMODULATED (empty weight store, modulation -> 1.0 cold start)'}`);

  // A11: load the seeded production weights into the engine's in-memory map.
  if (seedWeights) {
    const eng = engineModule.signalEngine as { loadPersistedLearningData: () => Promise<unknown>; getModelWeightForTest: (k: string) => number | undefined; getLearnedFeatureModulationForTest: (k: string) => number };
    await eng.loadPersistedLearningData();
    const rsiW = eng.getModelWeightForTest('rsi_weight');
    const rsiMod = eng.getLearnedFeatureModulationForTest('rsi_weight');
    console.log(`  A11: weights seeded. rsi_weight=${rsiW} -> modulation=${rsiMod}`);
  }

  // ── 4. Capture the engine's own console output ─────────────────────────────
  const rejections = new Map<string, number>();
  let emissions = 0;
  // ITEM 73(a) — FULL winning-strength distribution, not a summary. The engine
  // prints "Winning Strength: X (Min: Y)" on EVERY attempt that reaches the
  // conviction gate; the capture below previously discarded that line, so the
  // only observable was a pass/fail count and no percentile could be derived.
  // Re-anchoring a threshold requires the distribution it is compared against.
  const winningStrengths: number[] = [];
  const strengthDiffs: number[] = [];
  // ITEM 80(d) — TIER0_UNAVAILABLE counter for the DEGRADED banner.
  let tier0Unavailable = 0;
  const WINNING_STRENGTH_RE = /Winning Strength:\s*(-?\d+\.\d+)\s*\(Min:\s*(-?\d+\.?\d*)\)/;
  const STRENGTH_DIFF_RE = /Strength Difference:\s*(-?\d+\.\d+)/;
  let observedConvictionMin: number | null = null;
  const originalLog = console.log;
  const originalWarn = console.warn;
  let capturing = false;

  /**
   * ITEM 82 CORRECTION — inspect one captured console line.
   *
   * This used to live inline inside the `console.log` override ONLY. That was a
   * dead instrument for the TIER0 counter: the engine emits both
   * `[SRZoneTier0] TIER0_UNAVAILABLE` (srZoneTier0Service.ts:227) and
   * `[SRZoneTier0] TIER0_FALLBACK_TO_TIER1` (signalEngine.ts:3594,3599) via
   * `console.warn`, which was never intercepted. `tier0Unavailable` was therefore
   * structurally pinned at 0 no matter how degraded the run was, so the
   * "DEGRADED AND NOT COMPARABLE" guard below could never fire — and a reported
   * TIER0_UNAVAILABLE=0 was NOT evidence that TIER_0 zones were available.
   */
  const inspect = (msg: string): void => {
    const ws = WINNING_STRENGTH_RE.exec(msg);
    if (ws) {
      winningStrengths.push(Number(ws[1]));
      // Read the threshold the engine ACTUALLY compared against, rather than
      // trusting a constant quoted from the repo.
      if (observedConvictionMin === null) observedConvictionMin = Number(ws[2]);
    }
    const sd = STRENGTH_DIFF_RE.exec(msg);
    if (sd) strengthDiffs.push(Number(sd[1]));
    if (msg.includes('REJECTED') || msg.includes('BLOCKED') || msg.includes('STAND DOWN')) {
      const key = templatize(msg);
      rejections.set(key, (rejections.get(key) ?? 0) + 1);
      // A14: capture the FIRST rejection per attempt for mutually exclusive funnel.
      if (currentAttemptRejection === null) {
        currentAttemptRejection = key;
      }
    }
    // ITEM 80(d) — track TIER0 zone unavailability.
    if (msg.includes('TIER0_UNAVAILABLE') || msg.includes('TIER0_FALLBACK_TO_TIER1')) {
      tier0Unavailable += 1;
    }
  };

  console.log = (...args: unknown[]): void => {
    if (capturing) {
      inspect(args.map((a) => (typeof a === 'string' ? a : '')).join(' '));
      return;
    }
    originalLog(...args);
  };
  console.warn = (...args: unknown[]): void => {
    if (capturing) {
      inspect(args.map((a) => (typeof a === 'string' ? a : '')).join(' '));
      return;
    }
    originalWarn(...args);
  };

  // (The replay clock is installed above, before the engine import — see cause (2).)

  // Sampling controls. The full tape at STEP=5 is ~2,700 generateSignal calls and
  // runs for several minutes; --step lets a caller trade resolution for wall time.
  // Whatever is chosen must be IDENTICAL across a before/after pair, or the two
  // runs are not comparable.
  const argNum = (flag: string, fallback: number): number => {
    const idx = process.argv.indexOf(flag);
    if (idx < 0) return fallback;
    const parsed = Number(process.argv[idx + 1]);
    return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
  };
  const WARMUP = 300;
  const STEP = argNum('--step', 25);
  console.log(`  sampling: warmup ${WARMUP} bars, step ${STEP} bars`);
  const settings: ReplaySettings = buildReplaySettings();
  const ACCOUNT_BALANCE = 10_000;

  let attempts = 0;
  // B1 — exceptions are COUNTED BY TYPE, never swallowed.
  let exceptions = 0;
  const exceptionsByType = new Map<string, number>();
  let firstExceptionStack: string | null = null;
  // A14 — mutually exclusive funnel: first rejection per attempt.
  const funnelCounts = new Map<string, number>();
  let currentAttemptRejection: string | null = null;
  // A12 / CORRECTION 22 — per-attempt log. `direction` and `confidence` are read
  // off the emitted signal OBJECT, not scraped from a log line. The prior round
  // reported 10 emissions with no directions at all, which made them impossible to
  // compare against the user's "2 BUY + 1 SELL" benchmark — the entire point of the
  // window replay.
  const perAttemptLog: {
    ts: string;
    price: number;
    outcome: string;
    direction: string | null;
    confidence: number | null;
  }[] = [];
  capturing = true;
  try {
    for (let i = WARMUP; i < m1.length; i += STEP) {
      // A12: skip bars before the window start so we only step through the target window.
      if (windowStart > 0 && m1[i].timestamp < windowStart) continue;
      const slice = m1.slice(0, i);
      // "Now" is one minute past the last completed bar — the same relationship the
      // live engine has to its most recent closed M1 bar.
      replayNow = slice[slice.length - 1].timestamp + 60_000;
      currentAttemptRejection = null;
      try {
        engine.__injectBarSeriesForTestOnly(slice);
        setExternalPrice?.(slice[slice.length - 1].close, 'item57-replay');
        const result = await engine.generateSignal(settings, ACCOUNT_BALANCE, []);
        attempts += 1;
        if (result) emissions += 1;
        // A14: attribute this attempt to exactly ONE terminal outcome.
        const stage = result ? 'EMITTED' : (currentAttemptRejection ?? 'NO_REJECTION_LOGGED');
        funnelCounts.set(stage, (funnelCounts.get(stage) ?? 0) + 1);
        // A12 / CORRECTION 22: per-attempt detail INCLUDING direction + confidence.
        if (perAttempt || windowStart > 0) {
          const barTs = new Date(slice[slice.length - 1].timestamp).toISOString();
          const barPrice = slice[slice.length - 1].close;
          const sig = result as { type?: unknown; signalType?: unknown; direction?: unknown; confidence?: unknown } | null;
          const rawDir = sig?.type ?? sig?.signalType ?? sig?.direction ?? null;
          const rawConf = sig?.confidence;
          perAttemptLog.push({
            ts: barTs,
            price: barPrice,
            outcome: stage,
            direction: typeof rawDir === 'string' ? rawDir : null,
            confidence: typeof rawConf === 'number' ? rawConf : null,
          });
        }
      } catch (err: unknown) {
        // B1 — a throw is a HARNESS DEFECT, not a rejection-path outcome.
        // Counting it as a plain attempt (the old bare `catch {}`) is exactly
        // what kept F-0 invisible for the entire life of this instrument.
        attempts += 1;
        exceptions += 1;
        funnelCounts.set('EXCEPTION', (funnelCounts.get('EXCEPTION') ?? 0) + 1);
        const name = err instanceof Error ? `${err.name}: ${err.message}` : String(err);
        const key = templatize(name);
        exceptionsByType.set(key, (exceptionsByType.get(key) ?? 0) + 1);
        if (firstExceptionStack === null && err instanceof Error) {
          firstExceptionStack = (err.stack ?? err.message).split('\n').slice(0, 6).join('\n');
        }
      }
    }
  } finally {
    (globalThis as unknown as { Date: unknown }).Date = RealDate;
    Date.now = realDateNow;
    capturing = false;
    console.log = originalLog;
    console.warn = originalWarn;
  }

  // ── 5. Report ──────────────────────────────────────────────────────────────
  console.log(`\n${line}`);
  console.log('REPLAY RESULT (real bars)');
  console.log(line);
  console.log(`  generation attempts : ${attempts}`);
  console.log(`  signals emitted     : ${emissions}  (${pct(emissions, attempts)})`);
  // B1 — EXCEPTIONS is a first-class header field. An exception is a harness
  // defect: the run measured the harness, not the engine.
  console.log(`  EXCEPTIONS          : ${exceptions} of ${attempts} evaluations`);
  if (exceptions > 0) {
    console.log('');
    console.log(`  ${'!'.repeat(74)}`);
    console.log('  !!  HARNESS DEFECT — THIS RUN IS NOT A MEASUREMENT OF THE ENGINE');
    console.log(`  !!  ${exceptions} of ${attempts} evaluations threw before completing.`);
    console.log('  !!  Every post-conviction number below is VOID. Fix the harness, re-run.');
    console.log(`  ${'!'.repeat(74)}`);
    console.log('  exceptions by type:');
    for (const [type, n] of [...exceptionsByType.entries()].sort((a, b) => b[1] - a[1])) {
      console.log(`    ${String(n).padStart(5)}  ${type}`);
    }
    if (firstExceptionStack) {
      console.log('  first exception stack (6 frames):');
      for (const frame of firstExceptionStack.split('\n')) console.log(`    ${frame}`);
    }
    console.log('');
  }
  console.log(`  TIER0_UNAVAILABLE   : ${tier0Unavailable} of ${attempts} evaluations`);
  if (tier0Unavailable > 0) {
    console.log('');
    console.log('  ⚠️  DEGRADED AND NOT COMPARABLE — TIER0 zones were unavailable');
    console.log('  ⚠️  Cross-session comparison is INVALID when TIER0_UNAVAILABLE > 0');
    console.log('  ⚠️  Valid comparison requires TIER0_UNAVAILABLE = 0 AND same pinned tape-end');
  }
  console.log('\n  REJECTION REASONS (template-aggregated, top 25):');
  const sorted = [...rejections.entries()].sort((a, b) => b[1] - a[1]).slice(0, 25);
  if (sorted.length === 0) {
    console.log('    (none captured)');
  }
  for (const [reason, count] of sorted) {
    console.log(`    ${String(count).padStart(5)}  ${pct(count, attempts).padStart(6)}  ${reason}`);
  }

  // ── ITEM 73(a) — winning-strength distribution ─────────────────────────────
  const sortedWS = [...winningStrengths].sort((a, b) => a - b);
  const quantile = (arr: number[], q: number): number => {
    if (arr.length === 0) return NaN;
    const pos = (arr.length - 1) * q;
    const lo = Math.floor(pos);
    const hi = Math.ceil(pos);
    if (lo === hi) return arr[lo];
    return arr[lo] + (arr[hi] - arr[lo]) * (pos - lo);
  };
  console.log('\n  WINNING-STRENGTH DISTRIBUTION (every value at the conviction gate):');
  console.log(`    n                    : ${sortedWS.length}`);
  console.log(`    conviction min OBSERVED FROM THE ENGINE: ${observedConvictionMin ?? 'n/a'}`);
  if (sortedWS.length > 0) {
    console.log(`    min / max            : ${sortedWS[0].toFixed(4)} / ${sortedWS[sortedWS.length - 1].toFixed(4)}`);
    const mean = sortedWS.reduce((s, v) => s + v, 0) / sortedWS.length;
    console.log(`    mean                 : ${mean.toFixed(4)}`);
    for (const q of [0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99]) {
      console.log(`    q${(q * 100).toFixed(0).padStart(2)}                  : ${quantile(sortedWS, q).toFixed(4)}`);
    }
    if (observedConvictionMin !== null) {
      const passes = sortedWS.filter((v) => v >= (observedConvictionMin as number)).length;
      console.log(`    PASS RATE at ${observedConvictionMin}: ${passes}/${sortedWS.length} = ${pct(passes, sortedWS.length)}`);
    }
  }
  // The FULL vector, so a percentile can be derived off-harness without rerunning.
  console.log(`  WS_VECTOR_BEGIN ${sortedWS.map((v) => v.toFixed(4)).join(',')} WS_VECTOR_END`);
  // CORRECTION 5 — unsorted (tape-order) vector for index-for-index diffing across runs.
  console.log(`  WS_UNSORTED_BEGIN ${winningStrengths.map((v) => v.toFixed(4)).join(',')} WS_UNSORTED_END`);
  const sortedSD = [...strengthDiffs].sort((a, b) => a - b);
  console.log(`  SD_VECTOR_BEGIN ${sortedSD.map((v) => v.toFixed(4)).join(',')} SD_VECTOR_END`);

  // ITEM 80(c): verify the :6001 calibration penalty counter incremented
  const penalty25Fn = engineModule.getCalibrationPenalty25Stats as (() => { count: number; thenFailed: number }) | undefined;
  if (penalty25Fn) {
    const p25 = penalty25Fn();
    console.log(`  CALIBRATION_PENALTY_25: fired ${p25.count} time(s), thenFailed ${p25.thenFailed}`);
  }

  // A14 — MUTUALLY EXCLUSIVE FUNNEL. Each attempt is attributed to EXACTLY ONE
  // terminal outcome (the first rejection that fired, or EMITTED, or EXCEPTION).
  // The non-exclusive rejection map above can double-count; this cannot.
  const funnelSum = [...funnelCounts.values()].reduce((s, v) => s + v, 0);
  console.log('\n  MUTUALLY EXCLUSIVE FUNNEL (first terminal outcome per attempt):');
  console.log(`    sum of stages: ${funnelSum} (must equal attempts: ${attempts})`);
  const funnelSorted = [...funnelCounts.entries()].sort((a, b) => b[1] - a[1]);
  for (const [stage, count] of funnelSorted) {
    console.log(`    ${String(count).padStart(5)}  ${pct(count, attempts).padStart(6)}  ${stage}`);
  }
  const funnelMatch = funnelSum === attempts ? 'PASS' : 'FAIL';
  console.log(`    funnel reconciliation: ${funnelMatch}`);

  // A12 — per-attempt log for the 15-hour window replay.
  if (perAttemptLog.length > 0) {
    console.log('\n  PER-ATTEMPT LOG (window replay):');
    for (const entry of perAttemptLog) {
      console.log(`    ${entry.ts}  $${entry.price.toFixed(1)}  ${entry.outcome.slice(0, 100)}`);
    }
    const emitted = perAttemptLog.filter(e => e.outcome === 'EMITTED');
    console.log(`\n  WINDOW SUMMARY: ${perAttemptLog.length} attempts, ${emitted.length} emissions`);
    if (emitted.length > 0) {
      // CORRECTION 22 — directions are the deliverable, not an extra.
      console.log('  emitted signals (ts, price, DIRECTION, confidence):');
      for (const e of emitted) {
        const dir = e.direction ?? 'UNKNOWN';
        const conf = e.confidence === null ? 'n/a' : e.confidence.toFixed(4);
        console.log(`    ${e.ts}  $${e.price.toFixed(1)}  ${dir.padEnd(7)}  conf=${conf}`);
      }
      const buys = emitted.filter((e) => e.direction === 'BUY').length;
      const sells = emitted.filter((e) => e.direction === 'SELL').length;
      const unknown = emitted.length - buys - sells;
      console.log(`  DIRECTION TALLY: BUY=${buys} SELL=${sells} UNKNOWN=${unknown}`);
    }
  }

  await stampZoneBatch('after replay');

  console.log('');
}

main().catch((err: unknown) => {
  console.error('item57 harness failed:', err instanceof Error ? err.message : String(err));
  process.exit(1);
});
